/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien.Admin;

import Giaodien.Admin.Admin;
import Ham_xu_li.*;
import java.sql.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Minh
 */
public class MoHocPhan extends javax.swing.JFrame {

    Calendar now = Calendar.getInstance();
    public int year = now.get(Calendar.YEAR);
    //public static Connection conn = ConnectDB.getConnect();
    public static ResultSet resultset1 = null;
    public static ResultSet resultset2 = null;
    public static ResultSet resultset3 = null;
    public static PreparedStatement pst = null;

    /**
     * Creates new form AddSubject
     */
    public MoHocPhan() {
        initComponents();
        loadComboBox();
        System.out.print(this.institute.getSelectedItem());
        setDefaultCloseOperation(MoHocPhan.DISPOSE_ON_CLOSE);
    }

    public void loadComboBox() {
        this.semester_combo.addItem(String.valueOf(year - 1) + "1");
        this.semester_combo.addItem(String.valueOf(year - 1) + "2");
        this.semester_combo.addItem(String.valueOf(year - 1) + "3");
        this.semester_combo.addItem(String.valueOf(year) + "1");
        this.semester_combo.addItem(String.valueOf(year) + "2");
        this.semester_combo.addItem(String.valueOf(year) + "3");
        this.semester_combo.addItem(String.valueOf(year) + " - " + String.valueOf(year + 1));
        this.semester_combo.addItem(String.valueOf(year - 1) + " - " + String.valueOf(year));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<String>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        subject_id = new javax.swing.JTextField();
        subject_name = new javax.swing.JTextField();
        coefficient = new javax.swing.JComboBox<String>();
        institute = new javax.swing.JComboBox<String>();
        semester_combo = new javax.swing.JComboBox<String>();
        jButton2 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã học phần:");

        jLabel2.setText("Tên học phần:");

        jLabel3.setText("Viện:");

        jLabel4.setText("Hệ số:");

        jLabel5.setText("Kì học:");

        jButton1.setText("THÊM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        coefficient.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.3 - 0.7", "0.2 - 0.8", "0.5 - 0.5", "0.4 - 0.6" }));
        coefficient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coefficientActionPerformed(evt);
            }
        });

        institute.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Viện Công nghệ thông tin và Truyền thông", "Viện Điện tử - Viễn thông", "Viện Dệt may - Da giầy và Thời trang", "Viện Khoa học và Công nghệ Môi trường", "Viện Khoa học và Công nghệ nhiệt lạnh", "Viện Khoa học và Kỹ thuật Vật liệu", "Viện Kinh tế và Quản lý", "Viện Kỹ thuật hạt nhân và Vật lý môi trường", "Viện Kỹ thuật Hóa học", "Viện Ngoại ngữ", "Viện Sư phạm Kỹ thuật", "Viện Toán ứng dụng và Tin học", "Viện Vật lý Kỹ thuật", "Viện Điện", "Khoa Giáo dục Quốc phòng - An ninh", "Khoa Giáo dục Thể chất", "Khoa Lý luận Chính trị", "Viện Cơ khí", "Viện Cơ khí Động lực", "Viện Công nghệ Sinh học và Công nghệ Thực phẩm" }));

        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(46, 46, 46)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subject_name)
                            .addComponent(institute, 0, 529, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subject_id, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(semester_combo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(coefficient, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(subject_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(subject_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(institute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(coefficient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(semester_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coefficientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coefficientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coefficientActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Float coefficient_value = Float.parseFloat(this.coefficient.getSelectedItem().toString().substring(0, 3));
        String institute_value = (String) this.institute.getSelectedItem();
        Integer semester_value;
        if (this.semester_combo.getSelectedItem().toString().length() > 5) {
            semester_value = Integer.parseInt(this.semester_combo.getSelectedItem().toString().substring(0, 4));
        } else {
            semester_value = Integer.parseInt(this.semester_combo.getSelectedItem().toString());
        }
        if (this.subject_id.getText().length() == 0 || this.subject_name.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã học phần hoặc tên học phần", "Thông báo", 0);
        } else {
            Monhoc monhoc = new Monhoc(this.subject_id.getText(), semester_value, this.subject_name.getText(), coefficient_value, institute_value);
            resultset1 = Admin.admin.searchSubjectByParams(monhoc.getSubject_id(), monhoc.getSemester(), monhoc.getInstitute());
            try {
                if (resultset1.next()) {
                    JOptionPane.showMessageDialog(null, "rs1", "Thông báo", 0);
                    Admin.admin.updateSubject(monhoc, 0, 0);
                } else {
                    Admin.admin.insertSubject(monhoc);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Thêm học phần bị lỗi", "Thông báo", 0);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Admin admin = new Admin();
        admin.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoHocPhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> coefficient;
    private javax.swing.JComboBox<String> institute;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> semester_combo;
    private javax.swing.JTextField subject_id;
    private javax.swing.JTextField subject_name;
    // End of variables declaration//GEN-END:variables
}
