/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien.SinhvienTC;

import Giaodien.Main;
import Giaodien.SinhvienTC.DangKiHocPhan;
import static Giaodien.Main.user_id;
import static Giaodien.Main.name;
import Ham_xu_li.SinhVienNienChe;
import Ham_xu_li.SinhVienTinChi;
import javax.swing.JOptionPane;

/**
 *
 * @author duc
 */
public class SinhvienTC extends javax.swing.JFrame {

    /**
     * Creates new form SinhvienTC
     */
    public static Ham_xu_li.SinhVienTinChi sinhvien_tc = new SinhVienTinChi();
   
    public SinhvienTC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHello = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btDKhocphan = new javax.swing.JButton();
        btXemDsLop = new javax.swing.JButton();
        btVaodiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtHello.setText("Xin chao, ....");

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btDKhocphan.setText("Đăng kí học phần");
        btDKhocphan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDKhocphanActionPerformed(evt);
            }
        });

        btXemDsLop.setText("Xem danh sách lớp");
        btXemDsLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXemDsLopActionPerformed(evt);
            }
        });

        btVaodiem.setText("Xem điểm ");
        btVaodiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVaodiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtHello)
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDKhocphan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btVaodiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btXemDsLop, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHello)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDKhocphan, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btXemDsLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btVaodiem, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Ban chac chan muon thoat ?", "Thong bao", 2) == 0) {
            this.dispose();
            Main main = new Main();
            main.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btDKhocphanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDKhocphanActionPerformed
       this.setVisible(false);
       DangKiHocPhan dkhp = new DangKiHocPhan();
       dkhp.setVisible(true);
    }//GEN-LAST:event_btDKhocphanActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.txtHello.setText(xinchao());
    }//GEN-LAST:event_formWindowActivated

    private void btVaodiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVaodiemActionPerformed
        XemdiemTC mlist = new XemdiemTC();
        
        this.setVisible(false);
        mlist.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btVaodiemActionPerformed

    private void btXemDsLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXemDsLopActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DangkiLop dklop = new DangkiLop();
        dklop.setVisible(true);
    }//GEN-LAST:event_btXemDsLopActionPerformed
    public String xinchao(){
        return "Xin chao "+name+"";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhvienTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhvienTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhvienTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhvienTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhvienTC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDKhocphan;
    private javax.swing.JButton btVaodiem;
    private javax.swing.JButton btXemDsLop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel txtHello;
    // End of variables declaration//GEN-END:variables
}
